-- insert_roles_data.sql

INSERT INTO Role (name, description) VALUES ('Client', 'Client role, regular user');
INSERT INTO Role (name, description) VALUES ('Support', 'Support role, support only, NO DEALS');
INSERT INTO Role (name, description) VALUES ('Mod', 'Moderator role, moderation duties');
INSERT INTO Role (name, description) VALUES ('Admin', 'Administrator role, full access');

INSERT INTO User (id, email, avatar, cover, name, userid, roleId) VALUES 
('xLoy_BOT_AmrVYJiRO2kd', 'services@mydevify.com', 'https://www.mydevify.com/assets/index.494ac568.png', '/img/noCover.png', 'Support (Bot)', NULL, 1);


INSERT INTO Settings (
  sitename, 
  announcement, 
  offer, 
  logo, 
  theme, 
  discordLogs,
 exchangeSystem,
  storeSystem,
  ticketSystem
) VALUES (
  'MyHelpDesk', 
  'We Love Cats', 
  'Special offer available!', 
  'https://mydevify.com/assets/xLoyMybb.5944be68.png', 
  'dark', 
  false,
  false,
  false,
  false
);




-- Insert a new category with a specific ID
INSERT INTO Category (id, name) 
VALUES (1, 'Cat1');




INSERT INTO Service (
  image, 
  title, 
  description, 
  price,
  categoryId,
  amount,
  buyOrSellType,
  ShoppyCode,
  ShoppyCodeNoCrypto
) VALUES 
  ('1723499148818phone.svg', 'Service 1', 'Description of Service 1', 10.99, 1, 50, 'sell', '2Dh6TwY', 'oORWBGB'),
  ('1723499148818phone.svg', 'Service 2', 'Description of Service 2', 20.99, 1, 30, 'sell', '2Dh6TwY', 'oORWBGB'),
  ('1723499148818phone.svg', 'Example Service 1', 'Example Description 1', 12.00, 1, 40, 'sell', '2Dh6TwY', 'oORWBGB'),
  ('1723499148818phone.svg', 'Example Service 2', 'Example Description 2', 15.00, 1, 25, 'sell', '2Dh6TwY', 'oORWBGB'),
  ('1723499148818phone.svg', 'Example Service 3', 'Example Description 3', 18.00, 1, 35, 'sell', '2Dh6TwY', 'oORWBGB'),
  ('1723499148818phone.svg', 'Example Service 4', 'Example Description 4', 22.00, 1, 20, 'sell', '2Dh6TwY', 'oORWBGB');

INSERT INTO country (name, shortname, enabled) VALUES
('Afghanistan', 'AF', 1),
('Albania', 'AL', 1),
('Algeria', 'DZ', 1),
('Andorra', 'AD', 1),
('Angola', 'AO', 1),
('Antigua and Barbuda', 'AG', 1),
('Argentina', 'AR', 1),
('Armenia', 'AM', 1),
('Australia', 'AU', 1),
('Austria', 'AT', 1),
('Azerbaijan', 'AZ', 1),
('Bahamas', 'BS', 1),
('Bahrain', 'BH', 1),
('Bangladesh', 'BD', 1),
('Barbados', 'BB', 1),
('Belarus', 'BY', 1),
('Belgium', 'BE', 1),
('Belize', 'BZ', 1),
('Benin', 'BJ', 1),
('Bhutan', 'BT', 1),
('Bolivia', 'BO', 1),
('Bosnia and Herzegovina', 'BA', 1),
('Botswana', 'BW', 1),
('Brazil', 'BR', 1),
('Brunei', 'BN', 1),
('Bulgaria', 'BG', 1),
('Burkina Faso', 'BF', 1),
('Burundi', 'BI', 1),
('Cabo Verde', 'CV', 1),
('Cambodia', 'KH', 1),
('Cameroon', 'CM', 1),
('Canada', 'CA', 1),
('Central African Republic', 'CF', 1),
('Chad', 'TD', 1),
('Chile', 'CL', 1),
('China', 'CN', 1),
('Colombia', 'CO', 1),
('Comoros', 'KM', 1),
('Congo, Democratic Republic of the', 'CD', 1),
('Congo, Republic of the', 'CG', 1),
('Costa Rica', 'CR', 1),
('Croatia', 'HR', 1),
('Cuba', 'CU', 1),
('Cyprus', 'CY', 1),
('Czech Republic', 'CZ', 1),
('Denmark', 'DK', 1),
('Djibouti', 'DJ', 1),
('Dominica', 'DM', 1),
('Dominican Republic', 'DO', 1),
('East Timor', 'TL', 1),
('Ecuador', 'EC', 1),
('Egypt', 'EG', 1),
('El Salvador', 'SV', 1),
('Equatorial Guinea', 'GQ', 1),
('Eritrea', 'ER', 1),
('Estonia', 'EE', 1),
('Eswatini', 'SZ', 1),
('Ethiopia', 'ET', 1),
('Fiji', 'FJ', 1),
('Finland', 'FI', 1),
('France', 'FR', 1),
('Gabon', 'GA', 1),
('Gambia', 'GM', 1),
('Georgia', 'GE', 1),
('Germany', 'DE', 1),
('Ghana', 'GH', 1),
('Greece', 'GR', 1),
('Grenada', 'GD', 1),
('Guatemala', 'GT', 1),
('Guinea', 'GN', 1),
('Guinea-Bissau', 'GW', 1),
('Guyana', 'GY', 1),
('Haiti', 'HT', 1),
('Honduras', 'HN', 1),
('Hungary', 'HU', 1),
('Iceland', 'IS', 1),
('India', 'IN', 1),
('Indonesia', 'ID', 1),
('Iran', 'IR', 1),
('Iraq', 'IQ', 1),
('Ireland', 'IE', 1),
('Israel', 'IL', 1),
('Italy', 'IT', 1),
('Jamaica', 'JM', 1),
('Japan', 'JP', 1),
('Jordan', 'JO', 1),
('Kazakhstan', 'KZ', 1),
('Kenya', 'KE', 1),
('Kiribati', 'KI', 1),
('Korea, North', 'KP', 1),
('Korea, South', 'KR', 1),
('Kosovo', 'XK', 1),
('Kuwait', 'KW', 1),
('Kyrgyzstan', 'KG', 1),
('Laos', 'LA', 1),
('Latvia', 'LV', 1),
('Lebanon', 'LB', 1),
('Lesotho', 'LS', 1),
('Liberia', 'LR', 1),
('Libya', 'LY', 1),
('Liechtenstein', 'LI', 1),
('Lithuania', 'LT', 1),
('Luxembourg', 'LU', 1),
('Madagascar', 'MG', 1),
('Malawi', 'MW', 1),
('Malaysia', 'MY', 1),
('Maldives', 'MV', 1),
('Mali', 'ML', 1),
('Malta', 'MT', 1),
('Marshall Islands', 'MH', 1),
('Mauritania', 'MR', 1),
('Mauritius', 'MU', 1),
('Mexico', 'MX', 1),
('Micronesia', 'FM', 1),
('Moldova', 'MD', 1),
('Monaco', 'MC', 1),
('Mongolia', 'MN', 1),
('Montenegro', 'ME', 1),
('Morocco', 'MA', 1),
('Mozambique', 'MZ', 1),
('Myanmar', 'MM', 1),
('Namibia', 'NA', 1),
('Nauru', 'NR', 1),
('Nepal', 'NP', 1),
('Netherlands', 'NL', 1),
('New Zealand', 'NZ', 1),
('Nicaragua', 'NI', 1),
('Niger', 'NE', 1),
('Nigeria', 'NG', 1),
('North Macedonia', 'MK', 1),
('Norway', 'NO', 1),
('Oman', 'OM', 1),
('Pakistan', 'PK', 1),
('Palau', 'PW', 1),
('Palestine', 'PS', 1),
('Panama', 'PA', 1),
('Papua New Guinea', 'PG', 1),
('Paraguay', 'PY', 1),
('Peru', 'PE', 1),
('Philippines', 'PH', 1),
('Poland', 'PL', 1),
('Portugal', 'PT', 1),
('Qatar', 'QA', 1),
('Romania', 'RO', 1),
('Russia', 'RU', 1),
('Rwanda', 'RW', 1),
('Saint Kitts and Nevis', 'KN', 1),
('Saint Lucia', 'LC', 1),
('Saint Vincent and the Grenadines', 'VC', 1),
('Samoa', 'WS', 1),
('San Marino', 'SM', 1),
('Sao Tome and Principe', 'ST', 1),
('Saudi Arabia', 'SA', 1),
('Senegal', 'SN', 1),
('Serbia', 'RS', 1),
('Seychelles', 'SC', 1),
('Sierra Leone', 'SL', 1),
('Singapore', 'SG', 1),
('Slovakia', 'SK', 1),
('Slovenia', 'SI', 1),
('Solomon Islands', 'SB', 1),
('Somalia', 'SO', 1),
('South Africa', 'ZA', 1),
('South Sudan', 'SS', 1),
('Spain', 'ES', 1),
('Sri Lanka', 'LK', 1),
('Sudan', 'SD', 1),
('Suriname', 'SR', 1),
('Sweden', 'SE', 1),
('Switzerland', 'CH', 1),
('Syria', 'SY', 1),
('Taiwan', 'TW', 1),
('Tajikistan', 'TJ', 1),
('Tanzania', 'TZ', 1),
('Thailand', 'TH', 1),
('Togo', 'TG', 1),
('Tonga', 'TO', 1),
('Trinidad and Tobago', 'TT', 1),
('Tunisia', 'TN', 1),
('Turkey', 'TR', 1),
('Turkmenistan', 'TM', 1),
('Tuvalu', 'TV', 1),
('Uganda', 'UG', 1),
('Ukraine', 'UA', 1),
('United Arab Emirates', 'AE', 1),
('United Kingdom', 'GB', 1),
('United States', 'US', 1),
('Uruguay', 'UY', 1),
('Uzbekistan', 'UZ', 1),
('Vanuatu', 'VU', 1),
('Vatican City', 'VA', 1),
('Venezuela', 'VE', 1),
('Vietnam', 'VN', 1),
('Yemen', 'YE', 1),
('Zambia', 'ZM', 1),
('Zimbabwe', 'ZW', 1);
